server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost/cloud_test?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样值0-1 1全部采集
      probability: 1


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.nono.cloud.entities

eureka:
  client:
    register-with-eureka: true
    #抓取已有注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    #向Server发送心跳时间间隔
    #lease-renewal-interval-in-seconds: 1
    #心跳等待上限
    #lease-expiration-duration-in-seconds: 2

