server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #动态路由
      routes:
        - id: payment_routh  #路由ID建议唯一配合服务名
          #uri: http://localhost:8001  #匹配后提供的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**  #断言 路径匹配进行路由
            - After=2020-04-23T10:27:25.434+08:00[Asia/Shanghai]
            #- Cookie=username,test
            - Header=x-Request-Id, \d+  #请求头含有x-Request-Id的属性且值为整数

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
              - Path=/payment/lb/**



eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka